- name: Check OCP pre-requisites
  include_tasks: facts.yml
  tags: always

- name: Fix SELinux if required
  include_tasks: selinux.yml
  when: selinux_check.rc == 1
  tags: security

- name: Fix network interfaces
  include_tasks: network.yml
  tags: network

- name: Setup packages repositories
  include_tasks: repo.yml
  tags: repo, rhn

- name: Prepare dns
  include_tasks: dns.yml
  tags: dns

- name: Prepare ntp
  include_tasks: ntp.yml
  tags: ntp

- name: Prepare node
  include_tasks: prepare.yml
  tags: prepare

- name: Update node
  include_tasks: update.yml
  tags: update

- name: SSH key distribution
  include_tasks: ssh-keys.yml
  tags: ssh
