- block:
  - name: NTP | check and install chronyd
    package:
      name: chrony
      state: installed

  - name: NTP | setup ntp servers
    lineinfile:
      regexp: "^server.*"
      line: "server {{item}} iburst"
      path: /etc/chrony.conf
    with_items: "{{ocp_ntp_upstream}}"
    register: chrony_conf

  - name: NTP | restart chrony service after configuration
    service:
      name: chronyd
      state: restarted
      enabled: yes
    when: chrony_conf.changed

  - name: NTP | update OS timezone
    command: timedatectl set-timezone {{ocp_timezone}}
    when: ansible_date_time.tz != ocp_timezone

  - name: NTP | disable rtc sync
    command: timedatectl set-local-rtc 0
    when: ansible_date_time.tz != ocp_timezone

  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution_version >= '7'

- block:
  - name: NTP | check and install ntpd
    package:
      name: ntpd
      state: installed

  - name: NTP | set timezone
    lineinfile:
      regexp: "^ZONE="
      line: "ZONE={{gnc_timezone}}"
      path: /etc/sysconfig/clock
    when: ansible_date_time.tz != ocp_timezone

  - name: NTP | update OS timezone
    command: tzdata-update
    when: ansible_date_time.tz != ocp_timezone

  - name: NTP | setup ntp servers
    lineinfile:
      regexp: "^server.*"
      line: "server {{item}} iburst"
      path: /etc/ntp.conf
    with_items: "{{ocp_ntp_upstream}}"
    register: ntp_conf

  - name: NTP | stop ntp service to force sync
    service:
      name: ntpd
      state: stop
    when: ntp_conf.changed

  - name: NTP | force ntp sync
    command: ntpd -gq
    when: ntp_conf.changed

  - name: NTP | restart ntp service after configuration
    service:
      name: ntpd
      state: restarted
      enabled: yes
    when: ntp_conf.changed

  when: ansible_os_family != 'RedHat'
